apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: learning-platform

resources:
  - namespace.yaml
  - configmap.yaml
  - persistent-volumes.yaml
  - auth-service-deployment.yaml
  - course-service-deployment.yaml
  - learning-service-deployment.yaml
  - api-gateway-deployment.yaml
  - frontend-service-deployment.yaml
  - ingress.yaml

