apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-pv
  namespace: learning-platform
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/learning-platform/auth
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-pvc
  namespace: learning-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: course-pv
  namespace: learning-platform
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/learning-platform/course
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: course-pvc
  namespace: learning-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: learning-pv
  namespace: learning-platform
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/learning-platform/learning
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: learning-pvc
  namespace: learning-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

